### ISSUE TITLE
TypeError, conflict with the latest react native?

### ISSUE THREAD

**Issue by kazewonginc** [WrathChaos/react-native-bottom-bar#1]
I am using
```
    "react": "16.8.3",
    "react-native": "0.59.8",
```
and following all the instructions to test out this package and rendered errors as follows.

Please suggest how to overcome this.

![Screenshot 2019-05-26 at 6 11 34 PM](https://user-images.githubusercontent.com/49477900/58380306-1a2cf080-7fe2-11e9-91f5-9ef02df1c3e7.png)

**Comment by WrathChaos** [comment]
Hello @kazewonginc, 
Thank you for submitting this issue. I'm going to solve and release a new version tonight :)

**Comment by WrathChaos** [comment]
Hello again @kazewonginc,
Here is the new version: 

## [Release 0.1.52](https://github.com/WrathChaos/react-native-bottom-bar/releases/tag/0.1.52)

Please try and give me a feedback :) Also example is updated without Expo. 

Expo version is coming soon either :)
