### ISSUE TITLE
Android Shadow Problem

### ISSUE THREAD

**Issue by DonsWayo** [WrathChaos/react-native-bottom-bar#4]
On ios works well, on android not see the background bar shadow. Any idea?

![Screenshot 2019-07-31 at 18 17 43](https://user-images.githubusercontent.com/34981526/62229222-83085e80-b3bf-11e9-8506-fc4648b65900.png)

**Comment by WrathChaos** [comment]
Hello @DonsWayo, 
Unfortunately, iOS's shadow properties do not work on Android. However, I will add a elevation style just for Android. I will fix it ASAP.

**Comment by WrathChaos** [comment]
Hi again @DonsWayo,
I tried to add the shadow for BottomBar however nothing works properly... I even tried the 3rd party integrations but even them not working on Android properly. I cannot believe that whole React Native does not have a shadow solution for Android.

**Comment by WrathChaos** [comment]
Still working on with a third party Android shadow library which is currently in beta. 
[React Native Androw ](https://github.com/folofse/androw/tree/master/react-native-androw)

If it works, I will integrate it.

**Comment by WrathChaos** [comment]
@DonsWayo, Good news here :) 
Androw works great :O Finally we have a shadow on Android. Please try the new version:

## [Release 0.2.0](https://github.com/WrathChaos/react-native-bottom-bar/releases/tag/0.2.0)
